name: Deploy to AWS Staging Environment

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  ssh-deploy:
    name: ssh-deploy
    runs-on: ubuntu-latest
    steps:
    - name: cd in repo dir
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        command_timeout: 60m
        script: |
          set -e
          cd ~/cities-indicators-dashboard-urbanshift-staging
          git fetch --all
          git checkout staging
          git pull --ff-only
          docker build . -t staging-image
          docker rm -f staging-container || true
          docker run -d -p 4949:3838 --name staging-container --restart on-failure staging-image

