name: Deploy to AWS
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  ssh-deploy:
    name: ssh-deploy
    runs-on: ubuntu-20.04
    steps:
    - name: cd in repo dir
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AWS_IP }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: whoami
        